// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/campaign": {
    params: {};
  };
  "/arduino": {
    params: {};
  };
  "/account": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/campaign" | "/arduino" | "/account";
  };
  "routes/home.jsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/homeCampaign.jsx": {
    id: "routes/homeCampaign";
    page: "/campaign";
  };
  "routes/homeArduino.jsx": {
    id: "routes/homeArduino";
    page: "/arduino";
  };
  "routes/accountPage.jsx": {
    id: "routes/accountPage";
    page: "/account";
  };
};